export const columnsConstants = {
    SET_COLUMN_REQUEST: 'SET_COLUMN_REQUEST',
    SET_COLUMN_SUCCESS: 'SET_COLUMN_SUCCESS',
    SET_COLUMN_FAILURE: 'SET_COLUMN_FAILURE',

    SET_COLUMNS_REQUEST: 'SET_COLUMNS_REQUEST',
    SET_COLUMNS_SUCCESS: 'SET_COLUMNS_SUCCESS',
    SET_COLUMNS_FAILURE: 'SET_COLUMNS_FAILURE',

    DELETE_COLUMNS_REQUEST: 'DELETE_COLUMNS_REQUEST',
    DELETE_COLUMNS_SUCCESS: 'DELETE_COLUMNS_SUCCESS',
    DELETE_COLUMNS_FAILURE: 'DELETE_COLUMNS_FAILURE',

    SET_COLUMN_COMPONENT: 'SET_COLUMN_COMPONENT',

    SET_COLUMNS_COMPONENTS_REQUEST: 'SET_COLUMNS_COMPONENTS_REQUEST',
    SET_COLUMNS_COMPONENTS_SUCCESS: 'SET_COLUMNS_COMPONENTS_SUCCESS',
    SET_COLUMNS_COMPONENTS_FAILURE: 'SET_COLUMNS_COMPONENTS_FAILURE'
}
