export const composerConstants = {

    SET_REQUESTER_REQUEST: 'SET_REQUESTER_REQUEST',
    SET_REQUESTER_SUCCESS: 'SET_REQUESTER_SUCCESS',
    SET_REQUESTER_FAILURE: 'SET_REQUESTER_FAILURE',

    DELETE_REQUESTER_REQUEST: 'DELETE_REQUESTER_REQUEST',
    DELETE_REQUESTER_SUCCESS: 'DELETE_REQUESTER_SUCCESS',
    DELETE_REQUESTER_FAILURE: 'DELETE_REQUESTER_FAILURE',

    SET_USER_REQUEST: 'SET_USER_REQUEST',
    SET_USER_SUCCESS: 'SET_USER_SUCCESS',
    SET_USER_FAILURE: 'SET_USER_FAILURE',

    SET_USERS_REQUEST: 'SET_USERS_REQUEST',
    SET_USERS_SUCCESS: 'SET_USERS_SUCCESS',
    SET_USERS_FAILURE: 'SET_USERS_FAILURE',

    SET_EXTENSION_REQUEST: 'SET_EXTENSION_REQUEST',
    SET_EXTENSION_SUCCESS: 'SET_EXTENSION_SUCCESS',
    SET_EXTENSION_FAILURE: 'SET_EXTENSION_FAILURE',

    SET_EXTENSIONS_REQUEST: 'SET_EXTENSIONS_REQUEST',
    SET_EXTENSIONS_SUCCESS: 'SET_EXTENSIONS_SUCCESS',
    SET_EXTENSIONS_FAILURE: 'SET_EXTENSIONS_FAILURE',

    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

    SET_TEXT_BOX: 'SET_TEXT_BOX',
    SET_CHECK_BOX: 'SET_CHECK_BOX',
    SET_SIGN: 'SET_SIGN',
    SET_SIGN_PAD: 'SET_SIGN_PAD',

    DELETE_SIGN: 'DELETE_SIGN',
    DELETE_TEXT_BOX: 'DELETE_TEXT_BOX',
    DELETE_CHEKC_BOX: 'DELETE_CHEKC_BOX',
    DELETE_SIGN_PAD: 'DELETE_SIGN_PAD',

    SET_COMPONENTS_REQUEST: 'SET_COMPONENTS_REQUEST',
    SET_COMPONENTS_SUCCESS: 'SET_COMPONENTS_RSUCCESS',
    SET_COMPONENTS_FAILURE: 'SET_COMPONENTS_FAILURE',

    SEND_REQUEST: 'SEND_REQUEST',
    SEND_SUCCESS: 'SEND_RSUCCESS',
    SEND_FAILURE: 'SEND_FAILURE',
}
