export const contracterConstants = {
    CONTRACTER_REQUEST: 'CONTRACTER_LOAD_REQUEST',
    CONTRACTER_SUCCESS: 'CONTRACTER_LOAD_SUCCESS',
    CONTRACTER_FAILURE: 'CONTRACTER_LOAD_FAILURE',

    CONTRACTER_CLOSE: 'CONTRACTER_CLOSE',
    CONTRACTER_TOGGLE_TYPE: 'CONTRACTER_TOGGLE_TYPE',

    CONTRACTER_GUIDE_TYPE: 'CONTRACTER_GUIDE_TYPE'
}
