export const controllerConstants = {
    CONTROLLER_ZOOM_IN_REQUEST: 'CONTROLLER_ZOOM_IN_REQUEST',
    CONTROLLER_ZOOM_IN_SUCCESS: 'CONTROLLER_ZOOM_IN_SUCCESS',
    CONTROLLER_ZOOM_IN_FAILURE: 'CONTROLLER_ZOOM_IN_FAILURE',

    CONTROLLER_ZOOM_OUT_REQUEST: 'CONTROLLER_ZOOM_OUT_REQUEST',
    CONTROLLER_ZOOM_OUT_SUCCESS: 'CONTROLLER_ZOOM_OUT_SUCCESS',
    CONTROLLER_ZOOM_OUT_FAILURE: 'CONTROLLER_ZOOM_OUT_FAILURE',

    CONTROLLER_SET_SCALE_REQUEST: 'CONTROLLER_SCALE_REQUEST',
    CONTROLLER_SET_SCALE_SUCCESS: 'CONTROLLER_SCALE_SUCCESS',
    CONTROLLER_SET_SCALE_FAILURE: 'CONTROLLER_SCALE_FAILURE',

    CONTROLLER_SET_VIEW_TYPE_REQUEST: 'CONTROLLER_SET_VIEW_TYPE_REQUEST',
    CONTROLLER_SET_VIEW_TYPE_SUCCESS: 'CONTROLLER_SET_VIEW_TYPE_SUCCESS',
    CONTROLLER_SET_VIEW_TYPE_FAILURE: 'CONTROLLER_SET_VIEW_TYPE_FAILURE',

    CONTROLLER_TOGGLE_THUMBNAIL_REQUEST: 'CONTROLLER_TOGGLE_THUMBNAIL_REQUEST',
    CONTROLLER_TOGGLE_THUMBNAIL_SUCCESS: 'CONTROLLER_TOGGLE_THUMBNAIL_SUCCESS',
    CONTROLLER_TOGGLE_THUMBNAIL_FAILURE: 'CONTROLLER_STOGGLE_THUMBNAIL_FAILURE'
}
